# Generated by Django 3.2 on 2021-04-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('temp', models.DecimalField(decimal_places=1, max_digits=2)),
                ('oxi', models.DecimalField(decimal_places=0, max_digits=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
