# Generated by Django 3.2 on 2021-04-12 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Positivos',
            new_name='Positivo',
        ),
    ]
