# Generated by Django 3.2 on 2021-04-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20210413_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='positivo',
            name='validar',
            field=models.BooleanField(default=False),
        ),
    ]
