# Generated by Django 3.2 on 2021-04-13 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_positivo_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positivo',
            name='oxi',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='positivo',
            name='temp',
            field=models.FloatField(max_length=45, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
