# Generated by Django 3.2 on 2021-04-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20210413_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='positivo',
            name='vali',
            field=models.BooleanField(default=False),
        ),
    ]
