# Generated by Django 3.2 on 2021-04-29 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_auto_20210413_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positivo',
            name='oxi',
            field=models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='positivo',
            name='temp',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
